appinfo:
  name: track-my-day-gotth
  version: 0.0.1
  environtment: development # development, test, production
  secretkey: "secretkey"

server:
  port: 4000
  allowOrigins:
    - "*"
  timeout: 30

database:
  prod_db_path: "/var/data/prod/production.db"  # Production database path
  test_db_path: "/tmp/test/test.db"             # Test database path
  dev_db_path: "./db/development.db" #Development database path
