appinfo:
  name: track-my-day-gotth
  version: 0.0.1
  environtment: development # development, test, production
  secretkey: "secretkey"

server:
  port: 4000
  allowOrigins:
    - "*"
  timeout: 30

database:
  prod_db_path: "production.sqlite3"  # Production database path
  test_db_path: "test.sqlite3"             # Test database path
  dev_db_path: "development.sqlite3"            #Development database path
